### ISSUE TITLE
Best practice for adding necessary jar on classpath

### ISSUE THREAD

**Issue by lingyong** [lorettahe/ipython-clojure#1]
Thanks for the awesome work on the ipython-clojure!

I want to use it for my clojure project. So I started the ipython notebook using `ipython notebook --profile clojure` in my project directory and created a new notebook. And I used `(println (seq (.getURLs (java.lang.ClassLoader/getSystemClassLoader))))` to print out the classpath, it is returning `(#object[java.net.URL 0x9f4160a file:/home/lwang/ipython-clojure/bin/ipython-clojure])`

What I have been doing is adding the dependencies in my project to `ipython-clojure`'s `project.clj`, but this feels too hacky. So I am wondering is there a better way to add necessary jars on classpath? Like what "cider-jack-in" or "lein repl" did.

Thanks!

**Comment by lorettahe** [comment]
Hi,

Thank you for supporting this project! So just to let me understand the issue here fully - you want to dynamically add jars into the classpath when ipython is running?

**Comment by lorettahe** [comment]
I have tried running `ipython notebook --profile clojure` from my other Clojure projects' root directories, and they do load the leiningen dependencies specified there. Is that not the case there? Can you tell me how you are running ipython clojure?

**Comment by lingyong** [comment]
Hi! Thanks for getting back to me.

I ran the same command in my project's root directory, but it doesn't load the dependencies in `project.clj`, the only thing on the classpath is `/home/lwang/ipython-clojure/bin/ipython-clojure`.

**Comment by lorettahe** [comment]
Hey lingyong,

I've pushed a new change which should enable ipython clojure to automatically load dependencies for your local project. Please pull and make again before running ipython clojure.

Thank you for your support and let me know of any further issues!
Loretta

**Comment by lingyong** [comment]
It is working! :+1: Thanks for the support!
